server/authapp/urls.py
from django.conf.urls import url

import authapp.views as authapp

app_name = 'auth'

urlpatterns = [
    url('login/', authapp.login, name='login'),
    url('logout/', authapp.logout, name='logout'),
    url('register/$', authapp.register, name='register'),
    url('edit/$', authapp.edit, name='edit'),
]

server/mainapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.main_page, name='main_page'),
    path('catalog/', views.catalog_list, name='catalog'),
    path('<int:pk>/', views.product_detail, name='brooch'),
    path('contacts/', views.contacts, name='contacts'),
]

server/server/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('auth/', include('authapp.urls', namespace='auth')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/authapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class ShopUser(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatars', blank=True)
    age = models.PositiveIntegerField(verbose_name='возраст')

server/mainapp/models.py
from django.db import models


class Category(models.Model):

    title = models.CharField(
        max_length=250,
        unique=True
    )

    snippet = models.TextField(
        blank=True,
        null=True
    )

    def __str__(self):
        return self.title

    modified = models.DateTimeField(
        auto_now=True
    )

    created = models.DateTimeField(
        auto_now_add=True
    )


class Product(models.Model):

    alias = models.CharField(
        max_length=250,
        unique=True
    )

    title = models.CharField(
        max_length=250,
        unique=True
    )

    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE
    )

    image = models.ImageField(
        blank=True,
        null=True,
    )

    snippet = models.TextField(
        blank=True,
        null=True
    )

    cost = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=0
    )

    modified = models.DateTimeField(
        auto_now=True
    )

    created = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self):
        return self.alias

server/authapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from authapp.models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super(ShopUserRegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    # def clean_age(self):
    #     data = self.clean_age['age']
    #     if data < 18:
    #         raise forms.ValidationError("Вы слишком молоды!")
    #
    #     return data


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'email', 'age', 'avatar', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

    # def clean_age(self):
    #     data = self.clean_age['age']
    #     if data < 18:
    #         raise forms.ValidationError("Вы слишком молоды!")
    #
    #     return data

server/authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from authapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserEditForm
from django.contrib import auth
from django.urls import reverse


def login(request):
    title = 'Вход'

    login_form = ShopUserLoginForm(data=request.POST)
    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main_page'))

    content = {'title': title, 'login_form': login_form}
    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('main_page'))


def register(request):
    title = 'Регистрация'

    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = ShopUserRegisterForm

    content = {'title': title, 'register_form': register_form}

    return render(request, 'authapp/register.html', content)


def edit(request):
    title = 'Редактирование'

    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)

        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        edit_form = ShopUserEditForm(instance=request.user)

    content = {'title': title, 'edit_form': edit_form}

    return render(request, 'authapp/edit.html', content)

server/mainapp/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404

from . import models

links_menu = [
    {'href': 'main_page', 'name': 'главная'},
    {'href': 'catalog', 'name': 'каталог'},
    {'href': 'contacts', 'name': 'контакты'},
]


def main_page(request):

    content = {
        'links_menu': links_menu,
    }

    return render(request, 'mainapp/index.html', content)


def catalog_list(request):

    query = get_list_or_404(models.Product)
    query_category = get_list_or_404(models.Category)

    content = {
        'res_cat': query_category,
        'results': query,
        'links_menu': links_menu,
    }

    return render(request, 'mainapp/catalog.html', content)


def product_detail(request, pk):

    obj = get_object_or_404(models.Product, id=pk)

    content = {
        'instance': obj,
        'links_menu': links_menu,
    }

    return render(request, 'mainapp/brooch.html', content)


def contacts(request):

    content = {
        'links_menu': links_menu,
    }

    return render(request, 'mainapp/contacts.html', content)

server/authapp/templates/authapp/base.html
{% extends 'master.html' %}

{% load staticfiles %}

{% block page_title %}
    {{ title|title }}
{% endblock %}

{% block page_content %}
    <div class="container-log">
        <div class="login">
            <div class="h2 text-center head">
                Вход в систему
            </div>
        </div>
    </div>
    {% block log_form %}

    {% endblock %}

{% endblock %}

server/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}

{% load staticfiles %}

{% block log_form %}
    <form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ edit_form.as_p }}
        <br>
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'main_page' %}" class="">
            На главную
        </a>
    </button>
    <div class="user_avatar"><img src="/media/{{ user.avatar }}" height="100px"></div>
{% endblock %}

server/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}

{% load staticfiles %}

{% block log_form %}
    <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        {{ login_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="войти">
    </form>

    <button class="btn btn-round form-control">
        <a href="{% url 'auth:register' %}" class="">
            Зарегистрироваться
        </a>
    </button>
{% endblock %}

server/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}

{% load staticfiles %}

{% block log_form %}
    <form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ register_form.as_p }}
        <br>
        <input class="btn btn-round form-control" type="submit" value="Зарегистрироваться">
    </form>

{% endblock %}

server/mainapp/templates/mainapp/brooch.html
{% extends 'master.html' %}

{% load staticfiles %}

{% block page_title %}
Брошь - Чеширский кот
{% endblock %}

{% block page_menu %}

{% include 'mainapp/components/includes/inc_menu.html' %}

{% endblock %}

{% block page_content %}
	<div class="main first-letter-p">
		<h1>Брошь "Чеширский кот"</h1>
		<div class="description">
			<a href="{% static 'mainapp/img/cheshire_cat.jpg' %}" target=_blank>
				<img src="{% static 'mainapp/img/cheshire_cat.jpg' %}" alt="Брошь - лицо Чеширского кота" class="good-img">
			</a>
			<h2>Описание товара:</h2>
			<p class="short-description">Брошь из полимерной глины «Чеширский кот»</p>
			<button class="buy-button">Купить</button>
			<div class="clearfix"></div>
		</div>
		<h2>Характеристики товара:</h2>
		<ul class="good-features">
			<li>
				<h3>Материал:</h3> 
				<p>Полимерная глина, покрытая акриловым лаком, фурнитура подсеребро</p>
			</li>
			<li>
				<h3>Размер: </h3>
				<p>5 * 4 см</p>
			</li>
		</ul>
		
		<table>
			<caption>Подробная характеристика товара:</caption>
			<th>Наименование</th>
			<th>Использованные цвета</th>
			<th colspan="2">Материал</th>
			<th>Размер</th>

			<tr>
				<td rowspan="4">"Чеширский&nbsp;кот"</td>
				<td>Черный</td>
				<td rowspan="4">Полимерная глина</td>
				<td rowspan="4">Акриловый лак</td>
				<td rowspan="4">5 х 4 см</td>
			</tr>
			<tr>
				<td>Серый</td>
			</tr>
			<tr>
				<td>Розовый</td>
			</tr>
			<tr>
				<td>Голубой</td>
			</tr>
		</table>
		<h2>Подробное описание товара</h2>
		<p class="full-description">Уникальная брошь &laquo;Чеширский кот&raquo;, выполненная в&nbsp;стиле &laquo;квиллинг&raquo;, придется по&nbsp;вкусу всем любителям &laquo;Алисы в&nbsp;стране чудес&raquo; Льюиса Кэррола</p>
	</div>

{% endblock %}

server/mainapp/templates/mainapp/catalog.html
{% extends 'master.html' %}

{% load staticfiles %}

{% block page_title %}
Каталог
{% endblock %}

{% block page_menu %}

{% include 'mainapp/components/includes/inc_menu.html' %}

{% endblock %}

{% block page_content %}
	
	<div class="content">
		<h1>Каталог</h1>
		<ul class="main-menu">
			{% for item in res_cat %}
			<li class="{% if request.resolver_match.url_name == link.href %}
			active
			{% endif %}">
				<a href="#">{{ item.title|title }}</a>
			</li>
			{% endfor %}
		</ul>
		<div class="goods-catalog">
		{% for item in results %}

		{% include 'mainapp/components/includes/inc_goods.html' with good=item %}

		{% endfor %}
		</div>
	</div>



{% endblock %}

server/mainapp/templates/mainapp/components/includes/inc_goods.html
		{% load staticfiles %}
			<div class="good">
				<a href="{% url 'brooch' pk=good.id %}" >
                    <img class="catalog-img" src="{% static 'mainapp/img/' %}{{ good.image }}" alt="{{ good.title }}" >
					<p>{{ good.title }}</p>
				</a>
			</div>

server/mainapp/templates/mainapp/components/includes/inc_menu.html
<ul>
    {% if user.is_authenticated %}
	<li>
		<a href="{% url 'auth:edit' %}">
            {{ user.first_name|default:'User' }}
        </a>
	</li>
    {% endif %}
    <li>
        {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">Выйти</a>
        {% else %}
            <a href="{% url 'auth:login' %}">Войти</a>
            <a href="{% url 'auth:register' %}">Зарегистрироваться</a>
        {% endif %}
    </li>
</ul>

<ul class="main-menu">
	{% for link in links_menu %}
	<li class="{% if request.resolver_match.url_name == link.href %}
	active
	{% endif %}">
	<a href="{% url link.href %}">
		{{ link.name|title }}
	</a>
</li>
{% endfor %}

</ul>

server/mainapp/templates/mainapp/contacts.html
{% extends 'master.html' %}

{% load staticfiles %}

{% block page_title %}
Контакты
{% endblock %}

{% block page_menu %}

{% include 'mainapp/components/includes/inc_menu.html' %}

{% endblock %}

{% block page_content %}
<div class="main">
	<h1>Контакты</h1>
	<h2>Форма обратной связи</h2>
	<form action="#" method="post">
		<fieldset>
			<legend>Напишите нам!</legend>

			<label for="name">Ваше имя: </label>
			<input id="name" type="text" placeholder="Иван" name="user_name">

			<label for="email">Ваш e-mail: </label>
			<input id="email" type="email" placeholder="example@gmail.com" name="user_email"> 

			<label for="subj">Тема сообщения: </label>
			<input type="text" id="subj" placeholder="Subject" name="subject">

			<label for="message">Ваше сообщение:</label>
			<textarea name="text_message" id="message" placeholder="Your message"></textarea>

			<button type="submit">Submit</button>
			<button type="reset">Reset</button>
		</fieldset>
	</form>
	<h2>Адрес:</h2>
	<ul class="contact-info">
		<li>Tel: + 7 (777) 888-99-00</li>
		<li>Address: Russia, Kazan</li>
		<li>E-mail: sales@my_mag.ru</li>
	</ul>
	<h2>Как нас найти:</h2>
	<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d19156.426226468473!2d49.12961972757138!3d55.77777203279583!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sru!2sru!4v1534487373265" frameborder="0" allowfullscreen class="map"></iframe>
</div>
{% endblock %}

server/mainapp/templates/mainapp/index.html
{% extends 'master.html' %}

{% load staticfiles %}

{% block page_title %}
Магазин Необычностей
{% endblock %}

{% block page_menu %}

{% include 'mainapp/components/includes/inc_menu.html' %}

{% endblock %}

{% block page_content %}

		<div class="main">
			<a href="/"><h1>Магазин Необычностей</h1></a>

			<img src="{% static 'mainapp/img/welcome-img.jpg' %}" alt="Welcome to Unusualness Shop!" class="index-img">
			<div class="index-div">
				<p>Добро пожаловать в обычный магазин необычностей!</p>
				<p>В&nbsp;интернет-магазине Необчностей вы&nbsp;найдете уникальные вещи, сотворенные руками великих мастеров из&nbsp;полимерной глины! Никакие станки не&nbsp;заменят ту&nbsp;любовь и&nbsp;заботу, с&nbsp;которой сделаны все изделия. Вкладывая душу в&nbsp;свои работы, мастера как&nbsp;бы оживляют свои творения.</p>
				<p>Здесь обитают различные украшения, брелоки и&nbsp;броши, которые вы&nbsp;можете приобрести как себе, так и&nbsp;родным вам людям в&nbsp;качестве подарков.</p> 	
			</div>
		</div>

{% endblock %}

server/server/templates/master.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>
        {% block page_title %}
        {% endblock %}
    </title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'mainapp/style.css' %}">
</head>
<body>

	<div class="header">
		<a href="/"><span class="first-part-logo">un</span><span class="sec-part-logo">usualness</span></a>
		{% now "jS F Y H:i (T)" %}
        {% block page_menu %}
        {% endblock %}
    </div>
		

        {% block page_content %}
        {% endblock %}

	<div class="footer">
		<p>«Все права защищены» &copy;</p>
	</div>

</body>
</html>